### PR TITLE
Fix exporting from within module

### PR DESCRIPTION
**Pull request by KevinNovak**
Fix for:

> Exports and export assignments are not permitted in module augmentations.

image

### CODE REVIEW

**Comment by timotejroiko** [comment]
could you test it like this?

```js
export * from "discord.js"

declare module "discord.js-light" {
	import * as Discord from "discord.js"
	interface ClientOptions extends Discord.ClientOptions {
		cacheChannels?:boolean,
		cacheGuilds?:boolean,
		cachePresences?:boolean,
		cacheRoles?:boolean,
		cacheOverwrites?:boolean,
		cacheEmojis?:boolean
	}
	interface ClientEvents extends Discord.ClientEvents {
		rest:[{path:string,method:string,response:Promise<Buffer>}],
		shardConnect:[number,Discord.Collection<Discord.Snowflake,Discord.Guild>],
		guildEmojisUpdate:[Discord.Collection<Discord.Snowflake,Discord.GuildEmoji>]
	}
	class Client extends Discord.Client {
		public sweepUsers(lifetime: number): void;
		public sweepChannels(lifetime: number): void;
	}
}
```

**Comment by KevinNovak** [comment]
Here is what happens with that code when I run `tsc` (the typescript compiler):
image

You can install typescript compiler as well with:
`npm install -g typescript`

Then you should have the `tsc` command.

**Comment by timotejroiko** [comment]
how about this. No errors when running tsc, but im not sure if i ran it right ```ts
import * as Discord from "discord.js"
export * from "discord.js"

export class Client extends Discord.Client {
	public sweepUsers(lifetime: number): void;
	public sweepChannels(lifetime: number): void;
}

declare module "discord.js-light" {
	interface ClientOptions {
		cacheChannels?:boolean,
		cacheGuilds?:boolean,
		cachePresences?:boolean,
		cacheRoles?:boolean,
		cacheOverwrites?:boolean,
		cacheEmojis?:boolean
	}
	interface ClientEvents {
		rest:[{path:string,method:string,response:Promise<Buffer>}],
		shardConnect:[number,Discord.Collection<Discord.Snowflake,Discord.Guild>],
		guildEmojisUpdate:[Discord.Collection<Discord.Snowflake,Discord.GuildEmoji>]
	}
}
```

**Comment by KevinNovak** [comment]
With this code, I no longer need to import from discord.js, everything can be imported from discord.js-light:
image
image

This includes the extra client options combined with the original options from discord.js:
image

All compiles good. Looks great!

**Comment by timotejroiko** [comment]
Awesome. Add it to you PR and i'll merge

**Comment by KevinNovak** [comment]
Added. Thanks!

**Pull request merged**
