### PR TITLE
Ready event correctly fires

### PR DESCRIPTION
**Pull request by Ortovoxx**
The ready event will now fire when all shards are ready

### CODE REVIEW

**Comment by timotejroiko** [comment]
should emit Events.CLIENT_READY, not ShardEvents.READY, no?

Anyway no need to overcomplicate it. This should work:

```js
this.on(Discord.Constants.Events.SHARD_RESUME, () => {
    if(!this.readyAt) { this.ws.checkShardReady(); }
})
```

**Comment by Ortovoxx** [comment]
Yes you're right it should be `CLIENT_READY` it doesn't make much of a difference because both constants are "ready" and so it emits the same event but I will add it in for completeness

Not quite sure what you mean with `checkShardReady` ? That method doesn't seem to exist?

The reason I added the extra logic is to only emit the ready event once *all* shards were ready not just the first one.

**Comment by timotejroiko** [comment]
checkShardReady does exactly that

https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketManager.js#L394

**Comment by timotejroiko** [comment]
also, its better to use Discord.Constants.Events rather than import Constants from discord.js to account for possible modifications done to Discord in classes.js

**Comment by Ortovoxx** [comment]
Noted. Added those changes. Couldn't find that method but seems to do exactly what I intended ahaha

Thanks

**Pull request merged**
